---

stages:
  - test

# Use our custom image. See https://gitlab.com/testing-farm/images/-/tree/master/python-ci-image
# Because we still need py27 support, use the f32 based image
image: "quay.io/testing-farm/python-ci-image:f32"

#
# Poetry and MyPy colors
#
.colors:
  variables:
    TERM: "xterm"
    POETRY_ADDOPTS: "--ansi"
    MYPY_FORCE_COLOR: "1"
    PYTEST_ADDOPTS: "--color=yes"


#
# Some of the jobs require locale to be set, some fail with is. Those which need it can inherit this section.
#
.locale:
  variables:
    # See https://click.palletsprojects.com/en/7.x/python3/#python-3-surrogate-handling
    # Export these for Python 3.6 - from 3.7 forward, Python is smarter when picking
    # default locales.
    LC_ALL: "en_US.utf8"
    LANG: "en_US.utf8"

#
# Mark tests to run for merge requests
#
.merge-request:
  rules:
    - if: $CI_MERGE_REQUEST_IID

#
# TEST steps
#
.tests:
  extends: [.colors, .locale, .merge-request]
  before_script:
    - dnf -y install krb5-devel libcurl-devel popt-devel postgresql-devel libxml2-devel

# Build the container image
container:
  extends: .merge-request
  stage: test
  image: quay.io/buildah/stable:latest
  script:
    - dnf -y install make poetry python3.7
    - buildah login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io
    - IMAGE_TAG=$CI_PIPELINE_ID make build
    - IMAGE_TAG=$CI_PIPELINE_ID make push


# Run unit tests
#
# Note: this step also generates coverage report (HTML).
py27-unit-tests:
  extends: .tests
  stage: test
  script:
    - tox -v -e py27-unit-tests -- --cov=gluetool_modules_framework --cov-report=html:coverage-report
  artifacts:
    paths:
      - coverage-report

py37-unit-tests:
  extends: .tests
  stage: test
  script:
    - tox -v -e py37-unit-tests -- --cov=gluetool_modules_framework --cov-report=html:coverage-report
  artifacts:
    paths:
      - coverage-report

# Static analysis - pylint, flake8
py27-static-analysis:
  extends: .tests
  stage: test
  script:
    - tox -v -e py27-static-analysis

py37-static-analysis:
  extends: .tests
  stage: test
  script:
    - tox -v -e py37-static-analysis

# Static analysis - coala
#
# Note: coala integration is better done directly via gitlab's docker support
static-analysis-coala:
  extends: .merge-request
  stage: test
  image: quay.io/testing-farm/coala:latest
  script:
    - /usr/bin/coala --non-interactive --config .coafile

# Static analysis - type checks
type-check:
  extends: [.colors, .merge-request]
  stage: test
  script:
    - tox -v -e type-check

# Static analysis - pre-commit
pre-commit:
  extends: .merge-request
  stage: test
  script:
    - dnf -y install pre-commit
    - pre-commit run --all-files

# Installation Fedora
installation-fedora-py27:
  extends: .merge-request
  stage: test
  image: registry.fedoraproject.org/fedora:32
  script:
    # tmt requires rsync
    - dnf -y install python3-pip git rsync
    - pip3 install git+https://github.com/psss/tmt.git
    - tmt run -adddvvv provision -h local plan --name /plans/fedora/py27

installation-fedora-py37:
  extends: .merge-request
  stage: test
  image: registry.fedoraproject.org/fedora:36
  script:
    # tmt requires rsync
    - dnf -y install python3-pip git rsync
    - pip3 install git+https://github.com/psss/tmt.git
    - tmt run -adddvvv provision -h local plan --name /plans/fedora/py37

# Installation Centos Stream 8
installation-centos-stream-8:
  extends: .merge-request
  stage: test
  image: quay.io/centos/centos:stream8
  script:
    # tmt requires rsync
    - dnf -y install python3-pip git rsync
    - pip3 install git+https://github.com/psss/tmt.git
    - tmt run -adddvvv provision -h local plan --name /plans/centos-stream-8

# Installation RHEL8
# DISABLED temporarily due to ubi8 breakage
# fweimer> Root cause is the pre-8.6 GA UBI repos were pointing at the 8.5 composes
# Re-enable if this works: podman run registry.access.redhat.com/ubi8/ubi dnf -y install redhat-rpm-config
# installation-rhel8:
#   extends: .merge-request
#   stage: test
#   # using universal base images for RHEL8
#   # https://access.redhat.com/articles/4238681
#   image: registry.access.redhat.com/ubi8/ubi
#   script:
#     # tmt requires rsync
#     - dnf -y install python3-pip git rsync
#     - pip3 install git+https://github.com/psss/tmt.git
#     - tmt run -adddvvv provision -h local plan --name /plans/rhel8

# Generate documentation from the sources
#
# Note: executed for all commits in all branches to make sure it is actually possible
# to generate the documentation - serves as a sort of a "test" on its own. citool
# uses docstrings to generate command-line help, it is useful to check whether these
# docstrings are readable and sane.
py37-generate-docs:
  extends: .tests
  stage: test
  script:
    - tox -v -e py37-doctest -- ./docs
  artifacts:
    paths:
      - .tox/py37-doctest/tmp/docs/build/html

py27-generate-docs:
  extends: .tests
  stage: test
  script:
    - tox -v -e py27-doctest -- ./docs
  artifacts:
    paths:
      - .tox/py27-doctest/tmp/docs/build/html
